### ISSUE TITLE
Tracking: Support Key/value in produce and consumer

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#101]
* Produce records with arbitrary key/values
* Retrieve records with arbitrary key/values

- [ ] Support in Rust API #828 
- [ ] Support in CLI #830
- [ ] Support for Node Client #831
- [x] Determine whether we can implement Encode/Decode in a backwards compatible way
  - [x] Determine migration strategy for old-encoded records to new-encoded records
  - Conclusion: Clusters using new key/value encoding can read old records without migration. However, clients using the new key/value encoding must not produce records to old clusters using the old key/value encoding. Strategy to accommodate this is to bump `MINIMUM_PLATFORM_VERSION` to match the latest key/value encoding.
