### ISSUE TITLE
Tracking issue: Performance reporting improvements to `flv-test`

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1147]
This issue is tracking obtaining benchmark data from Open Messaging Benchmark using the java client.

* [ ] ~Add topic creation to Java client~ (https://github.com/infinyon/fluvio-client-java/issues/14) (Will use shell out to CLI as workaround. Not blocker.)
* [x] Terraform config for AWS resource creation
* [ ] Ansible playbook for installing and starting on AWS
* [x] Add statistical reporting to test driver (#1166)
* [ ] file based cluster/client config (#1167)
* [x] Producer P99
* [x] Consumer P99
* [x] E2E P99 (Produce w/ timestamp, consume calculates duration)
* [x] Multiple producer/consumer support (Assuming async, concurrent histogram support)
* [x] Multiple partition support (stretch, can the tests report the # of partitions too?)
* [ ] File-based payload support for tests (instead of only random generated)
* [ ] Time-based Max throughput test (stretch, can we support dynamically finding the max, or rate limiting?)
* [ ] Catchup-read test (Modified E2E, 2 Producer write 50% before 2 consumer starts)
* [ ] Mixed workload test (Modified E2E, 2 Producer write, 1 consumer read until 50%, then 2nd consumer starts)
* [ ] Add Perf tests to CI (#1085)
* [x] Producer Latency x time graphs
* [x] Consumer Latency x time graphs

**Comment by tjtelan** [comment]
A lot of this scope has either been de-prioritized, or it is captured in other issues. Closing
