### ISSUE TITLE
Release checklist for `0.9.0`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1254]
We would like to perform a "major" bump from `0.8.x` to `0.9.0` soon. I want to use this issue to collect tasks related to any breaking changes we would like to make before that release.

- [x] #1299
- [x] #1271
- [x] #1269
- [x] #1310
- [x] #1198 
- [x] #1334
- [x] https://github.com/infinyon/fluvio/issues/1338
- [x] #1301
- [x] Finish milestone `0.9.0`

---

# Release Checklist

Prior to releasing, the release manager should check the following:

- [x] Confirm that the sample code on the [fluvio.io] homepage is correct (Rust/Node/Python)
- [x] Review the "getting started" docs on fluvio.io/docs

[fluvio.io]: https://fluvio.io

To actually perform the release, the core steps are:

- [x] Run the `release.yml` workflow on GitHub Actions
- [x] Wait for workflow to complete successfully and apply `vX.Y.Z` tag to git
- [x] Publish any crates `fluvio` client depends on, followed by `fluvio` crate itself
- [x] Fast-forward `stable` branch to match `master` (may become automated)

After performing the release, the release manager should do the following in order
to prepare for the next release and announce the current release to the community:

- [x] Bump up the version in the `VERSION` file.
- [x] Add UNRELEASED section for new version to `CHANGELOG.md`.
- [ ] Announce the release on Discord and Twitter.

**Comment by sehz** [comment]
Done.  Greatwork everyone!
