### ISSUE TITLE
Release checklist: `0.9.1`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1374]
# Release 0.9.1

- [x] Confirm that the sample code on the [fluvio.io] homepage is correct (Rust/Node/Python)
- [x] Review the "getting started" docs on fluvio.io/docs

[fluvio.io]: https://fluvio.io

To actually perform the release, the core steps are:

- [x] Run the `release.yml` workflow on GitHub Actions
- [x] Wait for workflow to complete successfully and apply `vX.Y.Z` tag to git
- [x] Publish any crates `fluvio` client depends on, followed by `fluvio` crate itself
- [x] Fast-forward `stable` branch to match `master` (may become automated)

After performing the release, the release manager should do the following in order
to prepare for the next release and announce the current release to the community:

- [x] Bump up the version in the `VERSION` file.
- [x] Add UNRELEASED section for new version to `CHANGELOG.md`.
- [x] Announce the release on Discord and Twitter.

**Comment by sehz** [comment]
0.9.1 is out
