### ISSUE TITLE
Release checklist: `0.9.3`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1450]
## Pre-release

Prior to releasing, the release manager should check the following:

Update fluvio website doc (master):

- [x] Review the "getting started" docs.
- [x] Update Any API related docs.
- [x] Review rest of doc to ensure they are up to date.

Other dependent repos:
- [x] Update `infinyon/fluvio-smartstream-template` if needed.

## Release

First Lock master branch (TBD)

- [x] Publish all public crates.
- [x] Update `CHANGELOG.md` with release date.
- [x] Run the `release.yml` workflow on GitHub Actions.
- [x] Wait for workflow to complete successfully and apply `vX.Y.Z` tag to git.
- [x] Create PR from master to stable branch.  Get approval and merge it.
- [x] Update fluvio website to stable.

Unlock Master branch (TBD)

## Post-release

After performing the release, the release manager should do the following in order
to prepare for the next release and announce the current release to the community:

- [x] Bump up the version in the `VERSION` file.
- [x] Add UNRELEASED section for new version to `CHANGELOG.md`.
- [ ] Announce the release on Discord and Twitter.

**Comment by nicholastmosher** [comment]
I went to close this but I figured @simlay should get the satisfaction of checking it off 😄 nice job!

**Comment by simlay** [comment]
:tada:
