### ISSUE TITLE
[Tracking] Managed Connectors MVP

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#1541]
This task will be finished once we can do:
* `fluvio connector start --config ./my-config.toml`, it spins up and starts a connector in it's own pod
* `fluvio connector list` will list the connectors and their statuses
* `fluvio connector delete ${MY_CONNECTOR_NAME}`, gracefully stops the pod and deletes it.

- [x] https://github.com/infinyon/fluvio/issues/1537
- [x] https://github.com/infinyon/fluvio/issues/1536
- [x] https://github.com/infinyon/fluvio/issues/1540
- [x] https://github.com/infinyon/fluvio/pull/1499
- [x] https://github.com/infinyon/fluvio-connectors/pull/20
- [x] https://github.com/infinyon/fluvio-connectors/issues/24
- [x] https://github.com/infinyon/fluvio/issues/1648

**Comment by nacardin** [comment]
Done
