### ISSUE TITLE
Tracking: Separate SmartStream WASM registration from streaming

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1561]
Currently, SmartStreams are tightly coupled with StreamFetch requests. That is, the only time that a SmartStream may be provided to a cluster is when a consumer opens a stream and provided a WASM binary in that request. We need to separate these two processes so that SmartStreams may be managed independently of consumers making requests.

Action items:

- [ ] Create a new request type for uploading SmartStream WASM modules #1550 
  - Response should include a unique assigned ID for SmartStream
- [ ] Create a storage solution for WASM modules that are uploaded
  - Prefer on-disk in order to leverage wasmtime memory mapping and faster module instantiation
- [ ] Allow consumers to specify SmartStreams by ID rather than by binary upload

**Comment by sehz** [comment]
closing in favor of new `SmartModule` design
