### ISSUE TITLE
Consumer - Integrate Table spec into consume output

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1793]
We need integration of Table and the consume step.

Prior work this builds on:
* #1759 handles creating the Table spec
   * The Table module defines a set of keys we want to select from our data as columns (and any renaming of these column names)
* #1642 handles printing json data in a table format during `fluvio consume`
   * And supports table printing w/ smartstream

The bulk of this scope relies on an existing Table for key selection that are not top-level. The consumer client expects that data transformation occurs prior to printing (as opposed to the original shape of the data). 

However, based on #1759, we intended to also have client-side column selection on post-transformation data. (no column renaming expected via CLI though).

---

The consumer maintains the table buffer in `TableModel` struct, so we need to add in the Table spec transformations against the buffer.

`TableModel` needs to be refactored a bit so we can modify attributes about the table display with minimum need to touch of all the buffer data for display order purposes. Tables currently are rendered in a Row-oriented manner with the cell values printed in the order of how the json parser ordered their keys into a list.

The ordering is always alphabetical and we need to support:
- column ordering
- column renaming
- formatting options. 
- key inclusion (keying on non-top-level keys, selection of subsets) -- The idea here is we trim data we aren't going to use for display.

The CRD should contribute to all these features on the SPU-side, but there are some features that the client-side should be able to configure as a final override.

---

Chores I can do along that are related: 

Rename the table CRD to something a lot more specific. Tableformat? Tableview? Open to suggestions.

---

Tasks:
- [x] #1906
- [ ] #1907
- [ ] #1908
- [ ] CLI: Add Primary keys other than 1st column
- [ ] SPU-side: Filter out keys
- [ ] CLI: Standard cell auto-format types (Dates, time, duration, currency,)
