### ISSUE TITLE
[Release Checklist] 0.9.16

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2056]
# Release Checklist

The following checklist covers all the steps for running release.

For more detail, refer to [`RELEASE.md`](https://github.com/infinyon/fluvio/blob/master/RELEASE.md)

- [x] Create a [new issue](https://github.com/infinyon/fluvio/issues/new?template=release_checklist.md) with this checklist template
- [x] Inform team that release is about to begin
- [x] Review all the [Getting Started](https://www.fluvio.io/docs/get-started/mac/) and [API](https://www.fluvio.io/api/) docs. Verify if they are up to date or will need updates
- [x] Run the [`Release` workflow in Github Actions](https://github.com/infinyon/fluvio/actions/workflows/release.yml) (Retry at least once if failure)
- [x] Verify that the [crates publish to crates.io](https://github.com/infinyon/fluvio/actions/workflows/publish_crates.yml) succeeds (Retry at least once if failure)
- [x] Update `VERSION` and `CHANGELOG.md` files
- [x] Create a PR and use the `release_template.md` close this issue
- [ ] Announce new release in Discord

**Comment by tjtelan** [comment]
https://github.com/infinyon/fluvio/actions/runs/1651313512 The `CD_Release` workflow is broken because the output scraper picks up the channel output instead of the fluvio binary output (the installation order changed)
