### ISSUE TITLE
[Tracking] Client-side performance counters for producer/consumer

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2270]
Measuring the end to end performance of Fluvio is a little complicated at the moment. It would be great if this instrumentation could be available within the client so a user can opt-in to collect this data.

---

In `fluvio-test`, performance measurements for the fluvio client, such as throughput and latency, are done external to the client at the moment.

This is implemented by keeping track of the size of data sent/received, and tracking the start and end times of the action performed and then doing the math.

Resource usage (such as CPU, memory, disk and network i/o) is also inspected using external tools.

To validate the internal probes, we'll need to add external probes to `fluvio-test`'s test driver.

---

In the interest of encapsulating the required tools to this repo, initial support might be Linux/MacOS only.

Tasks:
- [ ] fluvio - Add latency + throughput instrumentation (default opt-in) to producer + consumer
- [ ] fluvio - Add resource profiling (default opt-in) to producer + consumer
- [ ] fluvio-cli - Add CLI options to allow a user to opt-in to these measurements and report result into file(s)
- [ ] fluvio-test - Add performance test w/ options for internal or external probes
- [ ] fluvio-test - Add latency + throughput for multiple producer/consumer processes
- [ ] fluvio-test - Add resource profiler for multiple producer/consumer processes
