### ISSUE TITLE
Tracking: Review public API of Rust client library

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#245]
The "public API" of a Rust library is all of the types and functions which are marked as `pub` and are accessible from consumers of the crate. We need to review the public API of Fluvio's client Rust crate (the `fluvio` package, located in `src/client-rs`).

In particular, we should evaluate the following aspects of the crate:

- [x] What is the minimum key functionality exposed by the client crate?
  - [x] Creating a client using default or specified configuration (polished in #290)
  - [x] Creating a producer that sends messages to a given topic and partition (polished in #290)
  - [x] Creating a consumer that receives messages from a given topic and partition (polished in #290)
- [x] What currently-public items can be made private for the time being?
- [x] What is the most logical organization of this functionality?
  - It seems advantageous to bundle all of Fluvio's functionality into a single client object `Fluvio`. This provides newcomers with a single entry point for getting started with writing applications. All other functionality is derived from the client object in one way or another.
  - Examples: the `Fluvio` client object has methods to construct producer and consumer objects, which can then be taken and used where necessary. Those producers and consumers do not have their own constructors, they _must_ be built from a Fluvio client. This creates the nice invariant that if you have a producer/consumer object, then you must have successfully connected to a cluster already.
- [x] How can this functionality be made consistent with other client APIs such as the CLI and the Node client?
  - The idea of having a central client type should apply to the Node client fairly easily.
  - Configuration is probably going to be an important item to standardize
- [x] How can we best document the API to be understandable to newcomers?
  - Write rustdocs for all public functions and structs
  - Be liberal in describing functionality beyond just individual functions. Let the docs refer to other functions or structs in order to pull the reader in and give them a path to explore the API
  - Add code samples to all rustdocs.
    - Note to developers: There are several great strategies for writing example code in rustdocs. First and foremost is to use the `no_run` tag on the code block since almost all of Fluvio's functionality is side-effecting. Secondly is to make good use of hidden code lines (ones that start with `#` in a rustdoc) in order to set up the context for an example. For example, if you want to show off a `TopicProducer` API, you need to write a code block that has access to an instance of a Fluvio client. But you can only get that by connecting to Fluvio. So what we can do instead is write a hidden function that takes Fluvio as an argument. E.g.
```rust
/// Creates a TopicProducer
/// 
/// # Example
///
/// ```no_run
/// # async fn do_get_producer(fluvio: &Fluvio) -> Result<(), FluvioError> {
/// let producer = fluvio.producer().await?;
/// # Ok(())
/// # }
/// ```
async fn producer() -> Result<TopicProducer, FluvioError> {}
```
The result of all of this is that the code will render nicely and also have compile-time checks built into the docs, without much code bloat in the examples
```rust
let producer = fluvio.producer().await?;
```
- [ ] Can we update the existing examples with the new API to prove it's adequacy?
  - [x] Echo example (#305)
  - [ ] CDC example (#315)

**Comment by sehz** [comment]
marking closing since CDC examples are tracked by #261
