### ISSUE TITLE
Tracking: Review public API of Node client

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#246]
The "public API" of a Node package is all of the exported items which are accessible from consumers of the package. We should review the public API of Fluvio's Node package.

In particular, we should evaluate the following aspects of the package:

- [x] What is the minimum key functionality exposed by the package?
- [x] What is the most logical organization of this functionality?
- [x] How can this functionality be made consistent with the other client APIs such as the CLI and the Rust crate?
- [x] How can we best document the API to be understandable to newcomers?
- [x] How to bundle native libraries with node modules 
- [x] publish node documentation
- [x] update sample apps with latest API changes;
- [x] update readme for fluvio client node with API changes;
- [x] add CD publish to npm for node client;

**Comment by sehz** [comment]
Please move this issue into https://github.com/infinyon/flv-client-node.
