### ISSUE TITLE
Tracking: SmartModule Development Kit

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2631]
Tracking list for SmartModule Development Kit (SMDK).

SMDK is a new top level CLI designed for SmartModule developer:

```
$ smdk new my-filter
Creating new SmartModule project...


$ smdk build

$ smdk
```

TODO:
- [x] Initial Skeleton
- [x] #2644
- [x] Project generation `smdk new` @EstebanBorai  #2621 
- [x] Build `smdk  build` @EstebanBorai 
- [x] Test `smdk test` @sehz 
- [x] Load `smdk  load` @sehz 
- [x] Publish `smdk publish` @digikata

**Comment by sehz** [comment]
Done!
