### ISSUE TITLE
tracking: Column Schema

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3164]
Tracking issue for https://github.com/infinyon/fluvio/issues/3081.

- [x] #3082
- [ ] Topic list
- [ ] Validate and store column data in key and record
- [x] https://github.com/infinyon/fluvio/issues/3167
- [ ] Topic produce with JSON
- [ ] Topic consume with Table
