### ISSUE TITLE
Tracking issue: Support secrets in Smartmodules

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#3224]
Allow SmartModules to accept secrets for parameters.

```
# transform.yaml
transforms:
  - uses: mygroup/verify-signature@0.1.0
    with:
      signing_key: ${{ secrets.SIGNING_KEY }}
```
```
# secrets.txt
SIGNING_KEY=0xDE027A148EA15EA5E32BEE472633A7D0
```
```
$ smdk test --text '{"payload": "asdf", "signature": "5257a869e7ecebeda32affa62cdca3fa51cad7e77a0e56ff536d0ce8e108d8bd"}' --transforms-file ./transforms.yaml --secrets ./secrets.txt
1 records outputed
{"valid": true}
```

- [ ] Secret support for `smdk test`
- [ ] Example and CLI test for CDK with secrets used in CDK
- [ ] Add to doc

**Comment by sehz** [comment]
@morenol, check if this is feasible now or needs more infrastructure changes

**Comment by morenol** [comment]
Secrets in smartmodules should be already supported on connectors. For supporting that on `smdk` we probably just need to move the Renderer to a different crate and use it in the smdk. For smartmodules we don't have access to `meta.secrets` so maybe for this use case we should assume that we will use the secrets defined in the file passed to `--secrets`

**Comment by morenol** [comment]
In cloud it should work as is. I will test it now

**Comment by sehz** [comment]
converted to tracking issue to include additional scopes

**Comment by morenol** [comment]
Using a configuration like this one works as expected. 

```
apiVersion: 0.1.0
meta:
  version: 0.2.2
  name: cat-facts
  type: http-source
  topic: cat-facts
  create-topic: true
  secrets:
    - name: KEY
http:
  endpoint: https://catfact.ninja/fact
  interval: 10s
transforms:
  - uses: contains-key
    with:
      key: ${{ secrets.KEY }}
```

**Comment by morenol** [comment]
The issue remaining would be to add this support to the `smdk`
