### ISSUE TITLE
Fluvio Version Manager

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3537]
Introduce Fluvio Version Manager (FVM) a CLI Tool used to switch between Fluvio Versions.
For our first release on the Fluvio Version Manager users will be able to download
Fluvio versions specifying the specific tag or update their Fluvio installation
directly from the FVM.

## Tasks (Integration)

The FVM integration is achieved command by command in the following order:

- [x] #3569 
- [x] #3573
- [x] #3596
- [x] #3644
- [x] Utilities and non-core features
  - [x] #3599
  - [x] #3600

### Improvements/Feedback

- [x] #3602
- [x] #3606
- [x] https://github.com/infinyon/fluvio/pull/3616
- [x] #3622
- [x] #3623
- [x] https://github.com/infinyon/fluvio/pull/3649
- [x] https://github.com/infinyon/fluvio/issues/3650

## Other Tasks

- [x] Update docs
  - [x] fluvio.io (docs)
  - [x] infinyon.com (docs & blogs)
- [ ] Remove `channels` and other operations covered by FVM from fluvio
- [ ] Add custom image for `Iot mirroring` & [update guide](https://infinyon.com/docs/guides/iot-mirroring-local/).
- [x] Ability to install stateful sets fluvio preview w/ added ssdk binary https://github.com/infinyon/fluvio-experiments/issues/187 
 
 ## Reference
[Prod RFD](https://github.com/infinyon/roadmap/blob/main/prod-rfd/fluvio-version-manager.md)

**Comment by digikata** [comment]
Engineering detail https://github.com/infinyon/roadmap/issues/161

**Comment by digikata** [comment]
New item: remove misc old version change and install commands
- fluvio install
- fluvio version switch

**Comment by digikata** [comment]
consider printing to std err deprecation if being kept this iteration
