### ISSUE TITLE
Tracking:  Timing and Socket related issues

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#459]
- [x] https://github.com/infinyon/fluvio/issues/373

- [x] https://github.com/infinyon/fluvio/issues/402

- [x] https://github.com/infinyon/fluvio/issues/398

- [ ] #409 

- [x] #473

**Comment by sehz** [comment]
Everything except #409 is fixed. closing this
