### ISSUE TITLE
tracking:  Command Extension Mechanism

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#496]
A new "Extension" mechanism will replace the current monolithic CLI.

Existing CLI commands will move into the following extensions:
* Consumer:  Topic, Partitions, Consume, Produce
* Cluster:   SPU, Install (start), Uninstall (stop/delete), check
* Engines:   SPU Engine, SC Engine (phase 2)

CLI will have commands related to extension management and profile:
* List Extension
* Install/Update/Uninstall Extensions
* Profile
* Self Update

CLI will no longer have explicit dependencies to any of the extensions in the future.
In the phase 1, CLI will be statically linked as before.

An extension can be implemented in any language.   The extensions will be be stored in the `extensions` folder in the fluvio configuration folder.   CLI will query each extension so it can be show commands to the user.

- [x] #463 (merge SPU and Custom SPU)
- [x] #427 (separate out SC and SPU)
- [x] #500 (Update Installer/Extension loader)
- [x ] #501 Metadata command protocol @simlay ( generate metadata from structop/clap form extension, CLI generates claps from metadata)
- [x] Separate Consumer extensions out of CLI
- [x] Move Cluster extension into Cluster crate (using feature flag, phase 1, bundle SC/SPU into cluster crates with extension feature, if image is still too big, we may decompose SC/SPU into a single engine)
- [x] Make local install as optional feature in the cluster

Questions
- name of extensions crates (`fluvio-extension-consumer`)
- Support development mode

Design:
- Extension trait?
- Run cluster executor (local,helm, future (docker, barebone, etc)
   - start/stopping SC/SPU
   - configuring SC/SPU/storage
   - remove/cleanup

publish fluvio as necessary using publisher @simlay

**Comment by sehz** [comment]
closing
