### ISSUE TITLE
Test runner infrastructure

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#566]
There are many tests that we would like to run where we want to have a `fluvio` client which is connected to a fresh fluvio cluster. We would like a test harness that can automatically provision this fresh cluster as easily as possible so that it is easy to run reproducible tests.

Implement procedure macro to mark test running test runner:

For example: 

```
#[fluvio_test(min_spu=2,topic=”test”)]
async fn smoke_test(config: TestConfig,client: Client) -> Result<(),...>
{
      let produce =  client.partition_producer(“topic”).await;
      …..

} 

#[cfg(type=”local”]
#[test]
Fn  smoke_test_runner()  {
  
       async fn smoke_test(config: TestConfig,client: Client) -> Result<(),...>
       }


       Let test_setup = new TestRunner()
       smoke_test(...)
      test_setup.cleanup()
  
}

#[fluvio_test(cluster=k8,min_spu=2,topic=”test”)]
async fn k8_test1(config: TestConfig,client: Client,cluster: &Cluster) -> Result<(),...>
{
      let produce =  client.partition_producer(“topic”).await;
      …..

} 

#[fluvio_test(cluster=local,min_spu=2,topic=”test”)]
async fn election_test(config: TestConfig,client: Client,cluster: &Cluster) -> Result<(),...>
{
      let produce =  client.partition_producer(“topic”).await;
      …..
     clutter.shutdown_spu(5001).await.expect(“shutdown”);
     ….

} 
```

They can be run using test runner:
```
fluvio_test_runner test smoke_test
fluvio_test_runner test --spu=2,
```

* Test runner run any test matches name pattern:  `smoke_test`, `smoke` (smoke_test,smoke_test1,test). similar to `cargo test`.  (Per requirements review, only a single test needs to be selected)  
* And tests must satisfy criteria matched in the test option (Optional minimum test criteria is declared via proc-macro attributes). 
    * e.g., `-k8` that test must able able to run on k8.
    * e.g., if test specifies, `min_spu=3`,  but test option specifics 1, then it will not able to criteria.  It should then print out how many tests it matches and failed to matches (name).
* Test runner can pass any of the options in the Test Runner as command line option [to be used for setting up a test environment, and to pass to a test]
* ~~Test runner can run group of tests using regex test runner name.~~ (Removed from scope, per requirements review)
* It is okay to only search for tests in `fluvio-integration-tests` crate.  The crate must only have tests.  
* Adding test do not requires changes in the test framework. (Tests must be collected dynamically. Not added manually in test runner)
* Satisfying existing test option.
* For topic name attribute name, test runner must ensure it exists prior to running test (Topic creation must be idempotent)
* Procedure macro must validate all inputs and gives proper error message the source

```
#[fluvio_test(cluster=local,min_spu4,topic=”test”)]
```

This should generate compilation error at the location of source
```
--> `min_spur4` is not valid attribute
```
It needs to:
- type check for argument types
- Allow all possible test options.  (A test cannot fail to start because it doesn't support any particular standard test option)

* For reporting, report as number of pass, fail,  and printout assert failure (similar to `cargo test`).

* Provide way to pass arbitrary key/value to Test.  Similar to cargo test:  `fluvio_test_runner test smoke_test --spu=2 -- -iteration=5`.   And then pass these options argument as part of TestOption

* There should time limit option.  If exceed time, then kill test and mark as failure

---

Tracking issues:
* [x] #878 - Add test reporting 
* [x] #879 - Add benchmark support
* [x] #880 - Add test timeouts
* [x] #881 - Make topic creation idempotent in test runner
* [x] #882 - Pass custom k/v to tests 
* [x] #883 - Collect tests dynamically in test runner build

**Comment by sehz** [comment]
Test runner should run against compiled version of Fluvio as well.

**Comment by tjtelan** [comment]
I don't know if my thinking about this is naive, but are we trying to avoid something by not using `cargo test`?

As I play around with integrating a proc macro to mark tests, it isn't becoming clearer to me how new tests should be added if we are building our own test runner.

One of the main benefits of `cargo test` that we are missing is their harness for gathering functions marked `#[test]`. Without this harness, we assume responsibility for manually collecting newly written tests in the runner. Seems like an easy task to forget.

---

If the proc macro is handling cluster init and test option declaration, I'm not clear what else we would need to pass in. So integration tests could possibly look more like this:

```
#[test]
#[fluvio_test(min_spu=2,topic=”test”)]
fn smoke_test() {
[...]
}
```

We would still organize tests into different mods per integration testing mode (`stress`, `smoke`, `longevity`, etc) and 

---

I am looking at [Diesel](https://github.com/diesel-rs/diesel/tree/master/diesel_tests) as an example for how we might organize integration tests, as well as [this blog post](https://joshleeb.com/blog/rust-integration-tests/).

**Comment by sehz** [comment]
Internally, `fluvio_test` can expand to use  `#[test]`.  That is up to implementation strategy.   
Problem with using `#[test]` directly is that it will be invoked when you run `cargo test`.   We don't integration test to be invoked as default

**Comment by tjtelan** [comment]
I recommend we use `cargo test` for our infrastructure harness and deprecate `flv-test` from CI. Any tests we don't want to run by default can be marked as `#[ignored]` and then be executed individually in CI. For example, running the smoke test with stdout:

`$ cargo test smoke -- --nocapture --ignored`

And we can run all the integration tests in parallel when we're ready for that.

The only workflows that `cargo test` wouldn't offer (w/r/t the current `flv-test` strategy):
- A CLI to override a test options for manual testing
- Local host cluster testing

The test run is configured with the example proc-macro and fn signature:
```rust
#[fluvio_test_macro::fluvio_test(topic = "default", ...)]
async fn example_test(config: TestOption: fluvio_config: FluvioConfig) {
    [User test]
}
```

and will transform to something like this
```rust
#[test] #[ignore]
fn example_test() {
    run_block_on(async move {
        let config : TestOption = ...
        [Deploy cluster]
        let fluvio_config : FluvioConfig = ...
        [Setup cluster]
        [User test]
        [Cleanup cluster]
    });
}
```

---

Based on current feedback about ideal changes, we should prioritize re-tuning the `TestOption` struct to:
* Clarify their function as standard words we use to describe dimensions of a Fluvio instance
* More simply delineate what is for cluster initialization (e.g. topic names, fresh client handles), vs. what is for the test case configuration (#X producers, #Y consumers, #Z iterations). 

It was also mentioned that we should consider "extra args" that aren't standard, so a test writer can use these key/values in only their test without interfering with rest of the integration test suite. (Perhaps `HashMap<&str, String>`?). Creeping feature? For sure, but it sounds plausibly useful if it is easy to support.

---

We need to split this task up into steps that can be introduced in pieces. With respect to #759, these are slightly more broken down steps to take:
(I'll create/update/reference the issues later and make this the tracking issue)

- [x] ~Clean up test runner to use programmatic fluvio-cluster rather than using fluvio cluster start CLI (#774)~
- [ ] Introduce proc macro `fluvio_test` to initialize a kubernetes cluster (#759) (Rename this issue)
- [ ] Update `TestOptions` struct to remove cluster setup information and rename field names
- [ ] Clean up macro magic variables and serde parsing hacks
- [ ] Add `cargo test` integration tests into CI
- [ ] Port all existing smoke tests into `cargo test` suite and deprecate `flv-test`
- [ ] Add Concurrency integration test in CI
- [ ] Add Multiple producer stress integration test in CI
- [ ] Configure hourly smoke tests
- [ ] Configure longevity tests (intervals TBD)
- [ ] Performance testing support (interval, random, longevity, standard benchmarking) (#777) (Rename this issue)
- [ ] Strategy for automating the testing of site example code
