### ISSUE TITLE
Tracking: Consumer Filter Smart Stream Phase 1 - Inline Smart Stream

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#816]
Given a filter such as the following:
```rust
#[wasm_bindgen(type="filter")]
/// Filter to check if the message contains a number
pub fn has_number(value: &[u8]) -> bool {
    let message = str::from_utf8(value).unwrap();
    return !message.chars().all(char::is_numeric);
}
```

Phase one developer build  inline filters via: `cargo build --bin sf1.rs --target wasm32-unknown-unknown --release`
- [ ]  `fluvio consume tp1 smartstream --inline-filter-bin sf1.bin`
    - [ ] Rust Client - `fluvio::consumer::ConsumerBuilder::new().filter(SmartStreamBuilder::from_bin_path("sf1.bin").build()?).build()?`
    - [ ] CLI - wraps rust client builder
    - [ ] SPU to actually run the filter - on disconnect, discard WASM code.
- [ ] `fluvio consume tp1 smartstream --inline-filter-rust sf1.rs`
    - [ ] compiles rust src to `wasm32-unkown-unkown` (do we have to require that the client has the rust toolchain and wasm32 as a target?)
    - [ ] `fluvio::consumer::ConsumerBuilder::new().filter(SmartStreamBuilder::from_rust_path("sf1.rs").build()?).build()?`

**Comment by sehz** [comment]
Basic SmartStream is now implemented
