### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#850]
Part of this task is to add a `RELEASES.md` someplace with a list of things that we need to check.

- [x] Review/run sample code on Home Page - Node @nicholastmosher 
- [x] Review/run sample code on Home Page - Rust @simlay
- [x]  ~Review/run sample code on Home Page - Python @simlay~ (not finished yet)
- [x] Review/run the Getting Started docs on fluvio.io/docs @nicholastmosher 
- [x] Rebase master into stable @simlay
- [x] Update `CHANGELOG.md` notes @simlay 
- [x] Publish rust crates
- [x] Run Release CI and mark as a stable release.
- [ ] Announce the release on Discord and twitter

**Comment by sehz** [comment]
Add running examples codes
