### ISSUE TITLE
Tracking: Improve Installation Experience

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#90]
This is tracking issue for improving user experience around installation:

- [ ] Distribute CLI binaries: #89 
- [ ] Better helm integration: #88 
- [x] Warn if release version is not available: #33 
- [ ] Prevent duplicate `minikubeCA` in `/etc/hosts` #220

**Comment by sehz** [comment]
closing
