### ISSUE TITLE
Tracking: Doc

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#93]
We need to make sure that our documentation is up to date before our open-source release. Here are the major items which need attention:

- [ ] CLI subcommands and args: #63
- [ ] Fluvio README.md
- [ ] High-level documentation on fluvio.io
- [ ] Rust API documentation
- [ ] Node API documentation

**Comment by sehz** [comment]
close in favor of individual issues
