### ISSUE TITLE
Release checklist: 0.8.0

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#991]
Things to do for the 0.8.0 release:

- [x] Update `CHANGELOG.md` notes @nicholastmosher 
- [x] Publish rust crates @nicholastmosher
- [x] Run Release CI and mark as a stable release @nicholastmosher 
- [x] Review/run the Getting Started docs on fluvio.io/docs @nicholastmosher
- [x] Update `stable` branch @nicholastmosher 
- [x] Review/run sample code on Home Page - Rust
- [x] Review/run sample code on Home Page - Node
- [x]  Review/run sample code on Home Page - Python
- [x] Milestone review to close/update/move issues
- [x] Announce the release on Discord and twitter

**Comment by ajhunyady** [comment]
@nicholastmosher changelog issues in 0.7.4 don't have hyperlinks https://github.com/infinyon/fluvio/blob/master/CHANGELOG.md

**Comment by nicholastmosher** [comment]
Ah dang. I'll fix that, thanks for pointing it out!
